baseURL = 'https://shonderdos.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.nl]
    languageCode = 'nl-NL'
    languageDirection = 'ltr'
    languageName = 'Nederlands'
    title = 'Serge Honderdos'
    weight = 1
  [languages.en]
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Serge Honderdos'
    weight = 2
