baseURL = 'https://shonderdos.nl/'
languageCode = 'en-us'
title = 'Serge Honderdos - Angular Developer Expert'
[params]
  author = 'Serge Honderdos'

[[menu.main]]
    name = "Experience"
    weight = 1
    url = "/experience/"
    params = { download = false }

[[menu.main]]
    name = "Download Resume"
    weight = 2
    url = "/cv-serge-honderdos-angular-expert.pdf"
    params = { download = true }
