name: "Example Push"
on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Create HTML file
        run: npm run build
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: index.html
      - name: Commit HTML file
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --global user.name 'Github Workflow'
          git config --global user.email 'github@workflow.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add index.html
          git commit -m "Updated HTML file"
          git push
