name: "Example Push"
on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '18'
      - name: Install dependencies
        run: npm install marked
      - name: Create HTML file
        run: curl https://raw.githubusercontent.com/shonderdos/shonderdos/main/README.md index.md
      - name: Commit HTML file
        run: |
          git config --global user.name 'Mr. Automation'
          git config --global user.email 'automations@aol.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add .
          git commit -m "Updated HTML file"
          git push


          
